---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
  - package-ecosystem: "pip"
    directory: "/backend"
    open-pull-requests-limit: 20
    schedule:
      interval: "daily"
  - package-ecosystem: "pip"
    directory: "/cli"
    open-pull-requests-limit: 20
    schedule:
      interval: "daily"
  - package-ecosystem: "pip"
    directory: "/connector"
    open-pull-requests-limit: 20
    schedule:
      interval: "daily"
  - package-ecosystem: "pip"
    directory: "/gui"
    open-pull-requests-limit: 20
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/frontend"
    open-pull-requests-limit: 20
    schedule:
      interval: "daily"
