name: Deploy MacOS

# yamllint disable-line rule:truthy
on:
  release:
    types:
      - published
  workflow_run:
    workflows:
      - "Build MacOS"
    branches:
      - master
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy-output:
    name: üë∑ Deploy Output to Release Assets
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: ‚§µÔ∏è Download Artifact - macos-out
        uses: dawidd6/action-download-artifact@v2.15.0
        with:
          name: macos-out
          path: macos-out
          workflow: ci.yml
          workflow_conclusion: success
      - name: üèó Compress directories
        run: |
          tar -czvf macos-out.tar.gz macos-out/*
      - name: ‚¨Ü Upload Artifacts to Release Assets
        uses: fnkr/github-action-ghr@v1.3
        env:
          GHR_PATH: macos-out.tar.gz
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GHR_REPLACE: true
  deploy-packages:
    name: üë∑ Deploy Packages to Release Assets
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: ‚§µÔ∏è Download Artifact - macos-dmg
        uses: dawidd6/action-download-artifact@v2.15.0
        with:
          name: macos-dmg
          path: macos-dmg
          workflow: ci.yml
          workflow_conclusion: success
      - name: ‚¨Ü Upload to Release Assets
        uses: fnkr/github-action-ghr@v1.3
        env:
          GHR_PATH: macos-dmg
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GHR_REPLACE: true
