name: Deploy Windows

# yamllint disable-line rule:truthy
on:
  release:
    types:
      - published
  workflow_run:
    workflows:
      - "Build Windows"
    branches:
      - master
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy-output:
    name: üë∑ Deploy Output to Release Assets
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: ‚§µÔ∏è Download Artifact - windows-out
        uses: dawidd6/action-download-artifact@v2.15.0
        with:
          name: windows-out
          path: windows-out
          workflow: ci.yml
          workflow_conclusion: success
      - name: üèó Compress directories
        run: |
          tar -czvf windows-out.tar.gz windows-out/*
      - name: ‚¨Ü Upload Artifacts to Release Assets
        uses: fnkr/github-action-ghr@v1.3
        env:
          GHR_PATH: windows-out.tar.gz
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GHR_REPLACE: true
  deploy-packages:
    name: üë∑ Deploy Packages to Release Assets
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: ‚§µÔ∏è Download Artifact - windows-setup
        uses: dawidd6/action-download-artifact@v2.15.0
        with:
          name: windows-setup
          path: windows-setup
          workflow: ci.yml
          workflow_conclusion: success
      - name: ‚¨Ü Upload to Release Assets
        uses: fnkr/github-action-ghr@v1.3
        env:
          GHR_PATH: windows-setup
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GHR_REPLACE: true
