---
name: "Package GUI"

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  release:
    types:
      - published
  workflow_call:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  package-python-pyinstaller-linux:
    uses: timmo001/workflows/.github/workflows/package-python-pyinstaller-linux.yml@master
    with:
      additional-pyinstaller-options: |
        --onedir \
        --windowed \
        --icon "resources/system-bridge.png" \
        --name "systembridgegui" \
        --collect-all "systembridgeshared" \
        --collect-all "systembridgegui" \
        --collect-all "typer" \
      create-setup: true
      entry-point-file: systembridge.py
      pre-package-command: |
        pip install -r requirements_gui_linux.txt
  package-python-pyinstaller-windows:
    uses: timmo001/workflows/.github/workflows/package-python-pyinstaller-windows.yml@master
    with:
      additional-pyinstaller-options: |
        --onedir `
        --windowed `
        --icon "resources/system-bridge.ico" `
        --name "systembridgegui" `
        --collect-all "systembridgeshared" `
        --collect-all "systembridgegui" `
        --collect-all "typer" `
      create-setup: true
      entry-point-file: application_gui.py
      pre-package-command: |
        pip install -r requirements_gui_windows.txt
